/**
 * FOGO De BRASIA 新宿 初期メニュー・スナップショット（出典: 食べログ）
 *
 * 出典URL:
 *   コース  https://tabelog.com/tokyo/A1304/A130401/13324936/party/
 *   料理    https://tabelog.com/tokyo/A1304/A130401/13324936/dtlmenu/
 *   ドリンク https://tabelog.com/tokyo/A1304/A130401/13324936/dtlmenu/drink/
 *
 * これは「初期登録用のソース・スナップショット」です。ページ上に明示された情報のみ。
 * 価格不明は price=null（import時 price_pending=true / 非公開）。推測で埋めない。
 * ランタイムで食べログを再取得しません。登録後は TENPO ONE の menu master が正。
 */
export const SOURCE = 'tabelog';
export const SOURCE_URLS = {
  course: 'https://tabelog.com/tokyo/A1304/A130401/13324936/party/',
  food: 'https://tabelog.com/tokyo/A1304/A130401/13324936/dtlmenu/',
  drink: 'https://tabelog.com/tokyo/A1304/A130401/13324936/dtlmenu/drink/',
};

// コース6件（席のみ予約はコース不要。course_id=null で成立）
export const COURSES = [
  { key: 'course-1', name: '厳選イチボの本格シュラスコ食べ放題・サラダバー&飲み放題付120分プラン', price: 5980, duration: 120, ayce: true, drinks: true, minParty: null, maxParty: null, notes: 'OPEN記念プラン（通常¥7,700）。当日満席で打ち切り。' },
  { key: 'course-2', name: '本格シュラスコ15種食べ放題｜サラダバービュッフェ＆飲み放題付き120分プラン', price: 7700, duration: 120, ayce: true, drinks: true, minParty: null, maxParty: null, notes: 'スタンダードディナー（通常¥8,800）。約30種のサラダバー・スイーツビュッフェ含む。' },
  { key: 'course-3', name: '人気のピッカーニャ！ランプ&ハラミ含む15種類のシュラスコ&サラダバー・TOKYO CRAFT含むビア&30種以上飲み放題150分プラン', price: 8800, duration: 150, ayce: true, drinks: true, minParty: null, maxParty: null, notes: 'プレミアムディナー。' },
  { key: 'course-4', name: '旬のフルーツスパークリング乾杯ドリンク付き&メッセージデザートプレート&シュラスコ120分食べ放題', price: 8000, duration: 120, ayce: true, drinks: false, minParty: null, maxParty: null, notes: '記念日・誕生日特典。乾杯スパークリング＆メッセージ入りデザートプレート付。' },
  { key: 'course-5', name: '貸切のご相談', price: 7700, duration: null, ayce: true, drinks: true, minParty: 40, maxParty: 99, notes: '貸切プラン（¥7,700〜）。コース内容・料理・飲み物・時間など相談可。' },
  { key: 'course-6', name: '16時〜17時入店でお得◎早割ディナー', price: 5500, duration: 120, ayce: true, drinks: true, minParty: null, maxParty: null, notes: '早割ディナー（通常¥6,500）。16:00〜17:00入店で割引。' },
];

// 料理38件（station=kitchen）。price=null は価格未確認（要オーナー設定）。
export const FOOD_CATEGORIES = [
  { name: 'シュラスコ（牛）', station: 'kitchen' },
  { name: '豚・鶏', station: 'kitchen' },
  { name: 'ラム', station: 'kitchen' },
  { name: 'サラダ', station: 'kitchen' },
  { name: 'サイド', station: 'kitchen' },
  { name: 'ブラジル料理', station: 'kitchen' },
  { name: 'ご飯・温菜', station: 'kitchen' },
  { name: 'デザート', station: 'kitchen' },
];
export const FOOD = [
  { key: 'food-1', cat: 'シュラスコ（牛）', name: 'ピッカーニャ（牛イチボ）200gm', price: 2000 },
  { key: 'food-2', cat: 'シュラスコ（牛）', name: 'フラウジーニャ（牛ハラミ）200gm', price: 2300 },
  { key: 'food-3', cat: 'シュラスコ（牛）', name: 'ビッフェ・デ・チョリソ（サーロイン）200gm', price: 2200 },
  { key: 'food-4', cat: 'シュラスコ（牛）', name: 'アルカトラ（牛ランプ）200gm', price: 1800 },
  { key: 'food-5', cat: 'シュラスコ（牛）', name: 'ガーリックステーキ 200gm', price: 1930 },
  { key: 'food-6', cat: 'シュラスコ（牛）', name: '自家製ローストビーフ 200gm', price: 1600 },
  { key: 'food-7', cat: 'シュラスコ（牛）', name: 'ペッパーステーキ 200gm', price: 1700 },
  { key: 'food-8', cat: 'シュラスコ（牛）', name: 'コステラ 450gm', price: 1900 },
  { key: 'food-9', cat: 'シュラスコ（牛）', name: '黒毛和牛グリル 200gm', price: 3500 },
  { key: 'food-10', cat: '豚・鶏', name: 'オンブロ・デ・ポルコ（豚肩ロース）', price: 1050 },
  { key: 'food-11', cat: '豚・鶏', name: 'リングイッサ（ブラジリアンソーセージ）2本', price: 990 },
  { key: 'food-12', cat: '豚・鶏', name: 'フランゴ（ローストチキン）', price: 960 },
  { key: 'food-13', cat: '豚・鶏', name: 'ローズマリーチキン', price: 950 },
  { key: 'food-14', cat: '豚・鶏', name: 'タンドリーチキン', price: 940 },
  { key: 'food-15', cat: '豚・鶏', name: 'ケージョンゴ（焼きチーズチキン）', price: 1630 },
  { key: 'food-16', cat: 'ラム', name: 'ラムチョップ 2P', price: 1800 },
  { key: 'food-17', cat: 'ラム', name: 'ラムステーキ', price: 1800 },
  { key: 'food-18', cat: 'サラダ', name: 'GANG オリジナルサラダ', price: 1150 },
  { key: 'food-19', cat: 'サラダ', name: 'タブレサラダ', price: 1000 },
  { key: 'food-20', cat: 'サラダ', name: 'ブラジリアンサルササラダ', price: 890 },
  { key: 'food-21', cat: 'サラダ', name: 'ポテトサラダ', price: 750 },
  { key: 'food-22', cat: 'サラダ', name: 'ヘルシーベジタブルプレート', price: 980 },
  { key: 'food-23', cat: 'サイド', name: 'ローストポテト', price: 750 },
  { key: 'food-24', cat: 'サイド', name: 'キノコのソテー', price: 890 },
  { key: 'food-25', cat: 'サイド', name: 'ナチョス', price: 1150 },
  { key: 'food-26', cat: 'サイド', name: '焼きえび', price: 1390 },
  { key: 'food-27', cat: 'サイド', name: '焼きナス＆ズッキーニプレート', price: 900 },
  { key: 'food-28', cat: 'ブラジル料理', name: 'ポンジケージョ（ブラジルの焼きチーズパン）2P', price: 850 },
  { key: 'food-29', cat: 'ブラジル料理', name: 'フェイジョン（ブラジリアンブラックビンス）', price: 700 },
  { key: 'food-30', cat: 'ご飯・温菜', name: 'コシヒカリライス', price: 400 },
  { key: 'food-31', cat: 'ご飯・温菜', name: 'ガーリックライス', price: 700 },
  { key: 'food-32', cat: 'ご飯・温菜', name: 'ガーリックトースト', price: 450 },
  { key: 'food-33', cat: 'ご飯・温菜', name: '日替わりカレー', price: 800 },
  { key: 'food-34', cat: 'デザート', name: 'アバカシ（焼きパイナップル）', price: 600 },
  { key: 'food-35', cat: 'デザート', name: 'フォンダンショコラ', price: 700 },
  { key: 'food-36', cat: 'デザート', name: 'バニラアイス', price: null },
  { key: 'food-37', cat: 'デザート', name: 'ティラミス', price: null },
  { key: 'food-38', cat: 'デザート', name: 'アサイー', price: 850 },
];

// ドリンク86件（station=drink）
export const DRINK_CATEGORIES = [
  '乾杯ドリンク', '生ビール', 'ウイスキー・ハイボール', 'サワー・酎ハイ', 'ノンアルコールビール',
  'カクテル', 'プレミアムカクテル', 'ソフトドリンク', '赤ワイン（グラス）', '白ワイン（グラス）',
  'スパークリング（グラス）', '赤ワイン（ボトル）', '白ワイン（ボトル）', 'ロゼワイン（ボトル）',
  'スパークリング（ボトル）', 'ノンアルコールワイン',
].map((name) => ({ name, station: 'drink' }));
export const DRINK = [
  { key: 'drink-1', cat: '乾杯ドリンク', name: '乾杯 旬のフルーツスパークリングワイン', price: 1200 },
  { key: 'drink-2', cat: '乾杯ドリンク', name: 'スパークリングワイン', price: 900 },
  { key: 'drink-3', cat: '乾杯ドリンク', name: 'ノンアルフルーツスパークリング', price: 900 },
  { key: 'drink-4', cat: '乾杯ドリンク', name: 'CHIVAS RIGAL HIGH-BALL', price: 990 },
  { key: 'drink-5', cat: '乾杯ドリンク', name: 'TOKYO CRAFT BEER 東京クラフト', price: 990 },
  { key: 'drink-6', cat: '乾杯ドリンク', name: '自家製サングリア', price: 700 },
  { key: 'drink-7', cat: '乾杯ドリンク', name: 'TEQUILLA SHOT', price: 700 },
  { key: 'drink-8', cat: '生ビール', name: '<香る>エール', price: 700 },
  { key: 'drink-9', cat: '生ビール', name: "Premium malt's パーフェクトサントリーP S B", price: 780 },
  { key: 'drink-10', cat: '生ビール', name: 'カールスバーグ', price: 900 },
  { key: 'drink-11', cat: '生ビール', name: 'シャンディガフ', price: 800 },
  { key: 'drink-12', cat: '生ビール', name: 'コークビア', price: 780 },
  { key: 'drink-13', cat: 'ウイスキー・ハイボール', name: '角ハイボール', price: 680 },
  { key: 'drink-14', cat: 'ウイスキー・ハイボール', name: 'コークハイボール', price: 700 },
  { key: 'drink-15', cat: 'ウイスキー・ハイボール', name: 'ジンジャーハイボール', price: 700 },
  { key: 'drink-16', cat: 'ウイスキー・ハイボール', name: 'ウィスキーロック', price: 670 },
  { key: 'drink-17', cat: 'サワー・酎ハイ', name: 'こだわりレモンサワー', price: 650 },
  { key: 'drink-18', cat: 'サワー・酎ハイ', name: 'グレープフルーツサワー', price: 650 },
  { key: 'drink-19', cat: 'サワー・酎ハイ', name: 'オレンジサワー', price: 650 },
  { key: 'drink-20', cat: 'サワー・酎ハイ', name: 'グレナデンサワー', price: 650 },
  { key: 'drink-21', cat: 'サワー・酎ハイ', name: 'メロンサワー', price: 650 },
  { key: 'drink-22', cat: 'サワー・酎ハイ', name: 'ライムサワー', price: 650 },
  { key: 'drink-23', cat: 'サワー・酎ハイ', name: 'ウーロンハイ', price: 650 },
  { key: 'drink-24', cat: 'サワー・酎ハイ', name: '緑茶ハイ', price: 650 },
  { key: 'drink-25', cat: 'ノンアルコールビール', name: 'ノンアルコールビール（ボトル）', price: 500 },
  { key: 'drink-26', cat: 'カクテル', name: 'ジンリッキー', price: 700 },
  { key: 'drink-27', cat: 'カクテル', name: 'ジンバック', price: 700 },
  { key: 'drink-28', cat: 'カクテル', name: 'ジンライム', price: 700 },
  { key: 'drink-29', cat: 'カクテル', name: 'ジントニック', price: 700 },
  { key: 'drink-30', cat: 'カクテル', name: 'ブルドック', price: 700 },
  { key: 'drink-31', cat: 'カクテル', name: 'モスコミュール', price: 700 },
  { key: 'drink-32', cat: 'カクテル', name: 'スクリュードライバー', price: 700 },
  { key: 'drink-33', cat: 'カクテル', name: 'ウォッカトニック', price: 700 },
  { key: 'drink-34', cat: 'カクテル', name: 'カシスソーダ', price: 700 },
  { key: 'drink-35', cat: 'カクテル', name: 'カシスオレンジ', price: 700 },
  { key: 'drink-36', cat: 'プレミアムカクテル', name: 'メキシコーク', price: 950 },
  { key: 'drink-37', cat: 'プレミアムカクテル', name: 'トムコリンズ', price: 950 },
  { key: 'drink-38', cat: 'プレミアムカクテル', name: 'テキーラサンライズ', price: 950 },
  { key: 'drink-39', cat: 'プレミアムカクテル', name: 'ボストンクーラー', price: 950 },
  { key: 'drink-40', cat: 'プレミアムカクテル', name: 'チャイナブルー', price: 950 },
  { key: 'drink-41', cat: 'プレミアムカクテル', name: 'ソルティードッグ', price: 950 },
  { key: 'drink-42', cat: 'プレミアムカクテル', name: 'スプモーニ', price: 950 },
  { key: 'drink-43', cat: 'プレミアムカクテル', name: 'マリブコーク', price: 950 },
  { key: 'drink-44', cat: 'プレミアムカクテル', name: 'キューバリバー', price: 950 },
  { key: 'drink-45', cat: 'プレミアムカクテル', name: 'ラムバック', price: 950 },
  { key: 'drink-46', cat: 'ソフトドリンク', name: 'ウーロン茶', price: 550 },
  { key: 'drink-47', cat: 'ソフトドリンク', name: '緑茶', price: 550 },
  { key: 'drink-48', cat: 'ソフトドリンク', name: 'オレンジジュース', price: 550 },
  { key: 'drink-49', cat: 'ソフトドリンク', name: 'グレープフルーツジュース', price: 550 },
  { key: 'drink-50', cat: 'ソフトドリンク', name: 'コカ・コーラ', price: 550 },
  { key: 'drink-51', cat: 'ソフトドリンク', name: 'ジンジャーエール', price: 550 },
  { key: 'drink-52', cat: 'ソフトドリンク', name: 'メロンソーダ', price: 550 },
  { key: 'drink-53', cat: 'ソフトドリンク', name: 'トニックウォーター', price: 550 },
  { key: 'drink-54', cat: '赤ワイン（グラス）', name: 'カルロロッシ（赤）', price: 650 },
  { key: 'drink-55', cat: '赤ワイン（グラス）', name: 'ウエストエンド・ブラックシラーズ', price: 880 },
  { key: 'drink-56', cat: '赤ワイン（グラス）', name: 'アングロ・イノチェンティ・カベルネ・ソーヴィニヨン', price: 1000 },
  { key: 'drink-57', cat: '赤ワイン（グラス）', name: 'トーラ・ネロ・ダヴォラ・ブラックラベル', price: 1300 },
  { key: 'drink-58', cat: '白ワイン（グラス）', name: 'カルロロッシ（白）', price: 650 },
  { key: 'drink-59', cat: '白ワイン（グラス）', name: 'カ・ボッタ・レ・ポッジエ・ビアンコ', price: 1000 },
  { key: 'drink-60', cat: '白ワイン（グラス）', name: 'テラマターアルタムシャルドネ', price: 1200 },
  { key: 'drink-61', cat: 'スパークリング（グラス）', name: 'ミオネット', price: 1000 },
  { key: 'drink-62', cat: 'スパークリング（グラス）', name: 'アルバトロス・クレマン・ド・ブルゴーニュ・ブリュット', price: 1500 },
  { key: 'drink-63', cat: '赤ワイン（ボトル）', name: 'マティナル カベルネ ソーヴィニヨン', price: 3270 },
  { key: 'drink-64', cat: '赤ワイン（ボトル）', name: 'カンテラ コレクション プリヴァダ 赤', price: 4560 },
  { key: 'drink-65', cat: '赤ワイン（ボトル）', name: 'シャトー レゾリュー 赤ラベル ACコルビエール', price: 6320 },
  { key: 'drink-66', cat: '赤ワイン（ボトル）', name: 'ビニャルバ レセルバ マルベック', price: 8840 },
  { key: 'drink-67', cat: '赤ワイン（ボトル）', name: 'テッレ デル マルケサート イネディット', price: 10650 },
  { key: 'drink-68', cat: '赤ワイン（ボトル）', name: 'テラマター アルタム カベルネソーヴィニヨン', price: 12500 },
  { key: 'drink-69', cat: '赤ワイン（ボトル）', name: 'ストーンヘッジ メリタージュ ナパ ヴァレー', price: 14800 },
  { key: 'drink-70', cat: '赤ワイン（ボトル）', name: 'カ ボッタ アルタ ヴァルポリチェッラ リパッソ', price: 17400 },
  { key: 'drink-71', cat: '赤ワイン（ボトル）', name: 'ストーンヘッジ リザーヴ カベルネ ソーヴィニヨン', price: 19600 },
  { key: 'drink-72', cat: '赤ワイン（ボトル）', name: 'レイニャック 赤', price: 23700 },
  { key: 'drink-73', cat: '白ワイン（ボトル）', name: 'マティナル シャルドネ', price: 3350 },
  { key: 'drink-74', cat: '白ワイン（ボトル）', name: 'リッチランド シャルドネ', price: 4650 },
  { key: 'drink-75', cat: '白ワイン（ボトル）', name: 'ペール ギヨ VDP ヴィオニエ', price: 6850 },
  { key: 'drink-76', cat: '白ワイン（ボトル）', name: 'ヴィッラ マッティエリ ソアヴェ クラシコ カンポルンゴ DOC', price: 7150 },
  { key: 'drink-77', cat: '白ワイン（ボトル）', name: 'ストーンヘッジ シャルドネ カリフォルニア', price: 9550 },
  { key: 'drink-78', cat: 'ロゼワイン（ボトル）', name: 'シャトー レゾリュー ロゼ ACコルビエール ロゼ', price: 4970 },
  { key: 'drink-79', cat: 'スパークリング（ボトル）', name: 'アルバトロス ブラン ド ブラン オーガニック', price: 4150 },
  { key: 'drink-80', cat: 'スパークリング（ボトル）', name: 'マス トゥーラー カバ ロゼ ブリュット オーガニック', price: 6300 },
  { key: 'drink-81', cat: 'スパークリング（ボトル）', name: 'ラ セルヴァ スプマンテ ブラン ド ノワール ブリュット', price: 10200 },
  { key: 'drink-82', cat: 'スパークリング（ボトル）', name: 'モンマルト ブリュット セクレ ド ファミーユ', price: 15700 },
  { key: 'drink-83', cat: 'スパークリング（ボトル）', name: 'ボランジェ キュヴェ スペシャル', price: 28900 },
  { key: 'drink-84', cat: 'ノンアルコールワイン', name: '〈スパークリング〉ディアムール ミュスカ ノンアルコール', price: 2680 },
  { key: 'drink-85', cat: 'ノンアルコールワイン', name: '〈白〉プティ エトワレ ノンアルコール シャルドネ', price: 3420 },
  { key: 'drink-86', cat: 'ノンアルコールワイン', name: '〈赤〉ソレイユ キュヴェ ユーコ フリー', price: 3970 },
];

// テーブル構成（ユーザー提供。総卓数はこの明細から自動計算＝15卓）
export const TABLES = [
  { name: 'T1', cap: 6 }, { name: 'T2', cap: 6 }, { name: 'T3', cap: 4 }, { name: 'T4', cap: 6 },
  { name: 'T5', cap: 6 }, { name: 'T6', cap: 10 }, { name: 'T7', cap: 4 }, { name: 'T8', cap: 6 },
  { name: 'T9', cap: 6 }, { name: 'T10', cap: 6 }, { name: 'T11', cap: 12 }, { name: 'T12', cap: 10 },
  { name: 'T13', cap: 8 }, { name: 'T14', cap: 6 }, { name: 'T15', cap: 6 },
];
