-- =============================================================
-- TENPO ONE — 00016 v0.3: 店頭待ち・店舗間移動WF・予算・日報・タスク・
-- お知らせ・マニュアル・承認ルール・異常検知閾値・テーブル配置・
-- 顧客統合・打刻厳密化・整合性制約・商品画像バケット
-- =============================================================

-- ---- 店頭待ち/キャンセル待ちの拡張 ----
alter table public.waitlist_entries
  add column ticket_no integer,          -- 当日受付番号（店舗×日で採番）
  add column called_at timestamptz,
  add column seated_at timestamptz,
  add column seat_preference text;
alter table public.waitlist_entries drop constraint waitlist_entries_status_check;
alter table public.waitlist_entries add constraint waitlist_entries_status_check
  check (status in ('waiting','called','contacted','converted','seated','expired','cancelled','no_show'));
create index idx_waitlist_store_date on public.waitlist_entries(store_id, desired_date, status);

-- ---- 店舗間在庫移動ワークフロー（申請→発送→受取。即時移動RPCは残置） ----
create table public.stock_transfers (
  id uuid primary key default gen_random_uuid(),
  transfer_no bigint generated by default as identity,
  organization_id uuid not null references public.organizations(id),
  from_store_id uuid not null references public.stores(id),
  to_store_id uuid not null references public.stores(id),
  status text not null default 'requested'
    check (status in ('requested','shipped','received','cancelled')),
  note text,
  requested_by uuid references public.profiles(id),
  shipped_at timestamptz,
  shipped_by uuid references public.profiles(id),
  received_at timestamptz,
  received_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid,
  updated_by uuid,
  check (from_store_id <> to_store_id)
);
create trigger trg_stock_transfers_updated_at before update on public.stock_transfers
  for each row execute function public.set_updated_at();
create index idx_stock_transfers_org on public.stock_transfers(organization_id, status);

create table public.stock_transfer_items (
  id uuid primary key default gen_random_uuid(),
  transfer_id uuid not null references public.stock_transfers(id) on delete cascade,
  inventory_item_id uuid not null references public.inventory_items(id),
  name text not null,
  quantity numeric(12,2) not null check (quantity > 0),
  unit text not null,
  created_at timestamptz not null default now()
);

alter table public.stock_transfers enable row level security;
create policy stock_transfers_select on public.stock_transfers for select
  using (public.app_is_cypress_admin() or (public.app_is_org_member(organization_id)
    and (public.app_has_store_access(organization_id, from_store_id)
         or public.app_has_store_access(organization_id, to_store_id))));
create policy stock_transfers_write on public.stock_transfers for all
  using (public.app_is_cypress_admin() or public.app_role_in(organization_id,
    array['org_owner','hq_admin','area_manager','store_manager','assistant_manager']))
  with check (public.app_is_cypress_admin() or public.app_role_in(organization_id,
    array['org_owner','hq_admin','area_manager','store_manager','assistant_manager']));
alter table public.stock_transfer_items enable row level security;
create policy stock_transfer_items_all on public.stock_transfer_items for all
  using (exists (select 1 from public.stock_transfers t where t.id = transfer_id))
  with check (exists (select 1 from public.stock_transfers t where t.id = transfer_id));

-- 発送: 送り元在庫を減算（負在庫禁止設定を尊重）
create or replace function public.ship_stock_transfer(p_transfer_id uuid)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_t public.stock_transfers%rowtype;
  v_line record;
  v_item public.inventory_items%rowtype;
  v_allow_negative boolean;
begin
  select * into v_t from public.stock_transfers where id = p_transfer_id for update;
  if not found then raise exception 'TRANSFER_NOT_FOUND'; end if;
  if v_t.status <> 'requested' then raise exception 'INVALID_STATUS'; end if;
  if not public.app_role_in(v_t.organization_id,
      array['org_owner','hq_admin','area_manager','store_manager','assistant_manager']) then
    raise exception 'FORBIDDEN';
  end if;
  select coalesce(allow_negative_stock, true) into v_allow_negative
  from public.store_settings where store_id = v_t.from_store_id;

  for v_line in select * from public.stock_transfer_items where transfer_id = p_transfer_id loop
    select * into v_item from public.inventory_items where id = v_line.inventory_item_id for update;
    if not v_allow_negative and v_item.current_quantity < v_line.quantity then
      raise exception 'INSUFFICIENT_STOCK: %', v_item.name;
    end if;
    insert into public.stock_movements
      (organization_id, store_id, inventory_item_id, movement_type, quantity, unit_cost,
       reason, transfer_group_id, to_store_id, business_date, created_by)
    values
      (v_t.organization_id, v_t.from_store_id, v_item.id, 'transfer_out', -v_line.quantity,
       v_item.avg_cost, '店舗間移動 #' || v_t.transfer_no, v_t.id, v_t.to_store_id,
       public.app_business_date(v_t.from_store_id), auth.uid());
    update public.inventory_items
    set current_quantity = current_quantity - v_line.quantity where id = v_item.id;
  end loop;

  update public.stock_transfers
  set status = 'shipped', shipped_at = now(), shipped_by = auth.uid(), updated_by = auth.uid()
  where id = p_transfer_id;
  perform public.log_audit(v_t.organization_id, v_t.from_store_id, 'inventory.transfer.ship',
    'stock_transfers', p_transfer_id::text, null, null, null);
  return jsonb_build_object('ok', true);
end $$;

-- 受取: 受取店の同名品目へ加算（なければ作成）。発送済みのみ受取可能
create or replace function public.receive_stock_transfer(p_transfer_id uuid)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_t public.stock_transfers%rowtype;
  v_line record;
  v_src public.inventory_items%rowtype;
  v_dst public.inventory_items%rowtype;
begin
  select * into v_t from public.stock_transfers where id = p_transfer_id for update;
  if not found then raise exception 'TRANSFER_NOT_FOUND'; end if;
  if v_t.status <> 'shipped' then raise exception 'INVALID_STATUS'; end if;
  if not public.app_role_in(v_t.organization_id,
      array['org_owner','hq_admin','area_manager','store_manager','assistant_manager']) then
    raise exception 'FORBIDDEN';
  end if;

  for v_line in select * from public.stock_transfer_items where transfer_id = p_transfer_id loop
    select * into v_src from public.inventory_items where id = v_line.inventory_item_id;
    select * into v_dst from public.inventory_items
    where organization_id = v_t.organization_id and store_id = v_t.to_store_id
      and name = v_line.name and status = 'active' limit 1;
    if not found then
      insert into public.inventory_items
        (organization_id, store_id, name, item_kind, category, unit,
         current_quantity, reorder_point, avg_cost, menu_item_id,
         purchase_unit, purchase_to_stock_factor, created_by)
      values
        (v_t.organization_id, v_t.to_store_id, v_line.name, v_src.item_kind, v_src.category,
         v_line.unit, 0, v_src.reorder_point, v_src.avg_cost, v_src.menu_item_id,
         v_src.purchase_unit, coalesce(v_src.purchase_to_stock_factor, 1), auth.uid())
      returning * into v_dst;
    end if;
    insert into public.stock_movements
      (organization_id, store_id, inventory_item_id, movement_type, quantity, unit_cost,
       reason, transfer_group_id, business_date, created_by)
    values
      (v_t.organization_id, v_t.to_store_id, v_dst.id, 'transfer_in', v_line.quantity,
       v_src.avg_cost, '店舗間移動 #' || v_t.transfer_no, v_t.id,
       public.app_business_date(v_t.to_store_id), auth.uid());
    update public.inventory_items
    set current_quantity = current_quantity + v_line.quantity where id = v_dst.id;
  end loop;

  update public.stock_transfers
  set status = 'received', received_at = now(), received_by = auth.uid(), updated_by = auth.uid()
  where id = p_transfer_id;
  perform public.log_audit(v_t.organization_id, v_t.to_store_id, 'inventory.transfer.receive',
    'stock_transfers', p_transfer_id::text, null, null, null);
  return jsonb_build_object('ok', true);
end $$;

-- ---- 予算管理 ----
create table public.budgets (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id),
  store_id uuid references public.stores(id), -- null=全社
  month date not null, -- 月初日
  sales_budget integer not null default 0,
  cost_rate_target numeric(5,2),
  labor_rate_target numeric(5,2),
  profit_target integer,
  guests_target integer,
  avg_spend_target integer,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid,
  updated_by uuid
);
create unique index idx_budgets_unique on public.budgets
  (organization_id, coalesce(store_id, '00000000-0000-0000-0000-000000000000'::uuid), month);
create trigger trg_budgets_updated_at before update on public.budgets
  for each row execute function public.set_updated_at();
alter table public.budgets enable row level security;
create policy budgets_select on public.budgets for select
  using (public.app_is_cypress_admin() or (public.app_is_org_member(organization_id)
    and public.app_has_store_access(organization_id, store_id)));
create policy budgets_write on public.budgets for all
  using (public.app_is_cypress_admin() or public.app_role_in(organization_id,
    array['org_owner','hq_admin','area_manager','store_manager']))
  with check (public.app_is_cypress_admin() or public.app_role_in(organization_id,
    array['org_owner','hq_admin','area_manager','store_manager']));

-- ---- 日報 ----
create table public.daily_reports (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id),
  store_id uuid not null references public.stores(id),
  business_date date not null,
  metrics jsonb not null default '{}'::jsonb, -- 売上/客数/客単価/差異/予約/キャンセル/廃棄/人件費（生成時snapshot）
  comment text,
  status text not null default 'draft' check (status in ('draft','submitted','approved')),
  submitted_by uuid references public.profiles(id),
  submitted_at timestamptz,
  approved_by uuid references public.profiles(id),
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid,
  updated_by uuid,
  unique (store_id, business_date)
);
create trigger trg_daily_reports_updated_at before update on public.daily_reports
  for each row execute function public.set_updated_at();
alter table public.daily_reports enable row level security;
create policy daily_reports_select on public.daily_reports for select
  using (public.app_is_cypress_admin() or (public.app_is_org_member(organization_id)
    and public.app_has_store_access(organization_id, store_id)));
create policy daily_reports_write on public.daily_reports for all
  using (public.app_is_cypress_admin() or (public.app_role_in(organization_id,
    array['org_owner','hq_admin','area_manager','store_manager','assistant_manager'])
    and public.app_has_store_access(organization_id, store_id)))
  with check (public.app_is_cypress_admin() or (public.app_role_in(organization_id,
    array['org_owner','hq_admin','area_manager','store_manager','assistant_manager'])
    and public.app_has_store_access(organization_id, store_id)));

-- ---- 店舗タスク・引継ぎ ----
create table public.store_tasks (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id),
  store_id uuid not null references public.stores(id),
  title text not null,
  body text,
  assignee_id uuid references public.profiles(id),
  due_date date,
  priority text not null default 'normal' check (priority in ('low','normal','high')),
  status text not null default 'open' check (status in ('open','in_progress','done','cancelled')),
  comments jsonb not null default '[]'::jsonb, -- [{by, name, at, body}]
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid,
  updated_by uuid
);
create index idx_store_tasks_store on public.store_tasks(store_id, status, due_date);
create trigger trg_store_tasks_updated_at before update on public.store_tasks
  for each row execute function public.set_updated_at();
alter table public.store_tasks enable row level security;
create policy store_tasks_select on public.store_tasks for select
  using (public.app_is_cypress_admin() or (public.app_is_org_member(organization_id)
    and public.app_has_store_access(organization_id, store_id)));
create policy store_tasks_write on public.store_tasks for all
  using (public.app_is_cypress_admin() or (public.app_role_in(organization_id,
    array['org_owner','hq_admin','area_manager','store_manager','assistant_manager','staff','part_time'])
    and public.app_has_store_access(organization_id, store_id)))
  with check (public.app_is_cypress_admin() or (public.app_role_in(organization_id,
    array['org_owner','hq_admin','area_manager','store_manager','assistant_manager','staff','part_time'])
    and public.app_has_store_access(organization_id, store_id)));

-- ---- 店舗お知らせ ----
create table public.announcements (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id),
  store_id uuid references public.stores(id), -- null=全店舗
  title text not null,
  body text not null,
  is_important boolean not null default false,
  publish_from date,
  publish_to date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid,
  updated_by uuid
);
create index idx_announcements_org on public.announcements(organization_id, publish_from);
create trigger trg_announcements_updated_at before update on public.announcements
  for each row execute function public.set_updated_at();

create table public.announcement_reads (
  id uuid primary key default gen_random_uuid(),
  announcement_id uuid not null references public.announcements(id) on delete cascade,
  profile_id uuid not null references public.profiles(id),
  read_at timestamptz not null default now(),
  unique (announcement_id, profile_id)
);

alter table public.announcements enable row level security;
create policy announcements_select on public.announcements for select
  using (public.app_is_cypress_admin() or (public.app_is_org_member(organization_id)
    and public.app_has_store_access(organization_id, store_id)));
create policy announcements_write on public.announcements for all
  using (public.app_is_cypress_admin() or public.app_role_in(organization_id,
    array['org_owner','hq_admin','area_manager','store_manager']))
  with check (public.app_is_cypress_admin() or public.app_role_in(organization_id,
    array['org_owner','hq_admin','area_manager','store_manager']));
alter table public.announcement_reads enable row level security;
create policy announcement_reads_own on public.announcement_reads for all
  using (profile_id = auth.uid()) with check (profile_id = auth.uid());
create policy announcement_reads_view on public.announcement_reads for select
  using (exists (select 1 from public.announcements a where a.id = announcement_id));

-- ---- マニュアル（Storageは documents バケットの org/manuals/ 配下を使用） ----
create table public.manuals (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id),
  store_id uuid references public.stores(id), -- null=全店共通
  title text not null,
  category text not null default 'other'
    check (category in ('service','hygiene','cooking','register','attendance','emergency','other')),
  file_path text,  -- Storage（documentsバケット）
  url text,        -- 外部URL
  note text,
  status text not null default 'active' check (status in ('active','deleted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid,
  updated_by uuid,
  check (file_path is not null or url is not null)
);
create trigger trg_manuals_updated_at before update on public.manuals
  for each row execute function public.set_updated_at();
alter table public.manuals enable row level security;
create policy manuals_select on public.manuals for select
  using (public.app_is_cypress_admin() or (public.app_is_org_member(organization_id)
    and public.app_has_store_access(organization_id, store_id)));
create policy manuals_write on public.manuals for all
  using (public.app_is_cypress_admin() or public.app_role_in(organization_id,
    array['org_owner','hq_admin','area_manager','store_manager']))
  with check (public.app_is_cypress_admin() or public.app_role_in(organization_id,
    array['org_owner','hq_admin','area_manager','store_manager']));

-- ---- 承認ルール（金額帯別の必要承認ロール） ----
create table public.approval_rules (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id),
  target text not null check (target in ('invoice','expense','petty_cash','purchase_order')),
  min_amount integer not null default 0,
  max_amount integer, -- null=上限なし
  approver_role text not null check (approver_role in
    ('store_manager','area_manager','hq_accounting','hq_admin','org_owner')),
  allow_self_approve boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid,
  updated_by uuid
);
create index idx_approval_rules_org on public.approval_rules(organization_id, target, min_amount);
create trigger trg_approval_rules_updated_at before update on public.approval_rules
  for each row execute function public.set_updated_at();
alter table public.approval_rules enable row level security;
create policy approval_rules_select on public.approval_rules for select
  using (public.app_is_cypress_admin() or public.app_is_org_member(organization_id));
create policy approval_rules_write on public.approval_rules for all
  using (public.app_is_cypress_admin() or public.app_role_in(organization_id, array['org_owner','hq_admin']))
  with check (public.app_is_cypress_admin() or public.app_role_in(organization_id, array['org_owner','hq_admin']));

-- ---- 異常検知の閾値（org既定 + 店舗override の継承パターン実装） ----
create table public.alert_rules (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id),
  store_id uuid references public.stores(id), -- null=企業既定
  rule_key text not null check (rule_key in
    ('cash_difference_yen','discount_rate_percent','void_count','cost_rate_percent',
     'labor_rate_percent','waste_amount_yen','sales_drop_percent')),
  threshold numeric(12,2) not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid,
  updated_by uuid
);
create unique index idx_alert_rules_unique on public.alert_rules
  (organization_id, coalesce(store_id, '00000000-0000-0000-0000-000000000000'::uuid), rule_key);
create trigger trg_alert_rules_updated_at before update on public.alert_rules
  for each row execute function public.set_updated_at();
alter table public.alert_rules enable row level security;
create policy alert_rules_select on public.alert_rules for select
  using (public.app_is_cypress_admin() or public.app_is_org_member(organization_id));
create policy alert_rules_write on public.alert_rules for all
  using (public.app_is_cypress_admin() or public.app_role_in(organization_id,
    array['org_owner','hq_admin','area_manager','store_manager']))
  with check (public.app_is_cypress_admin() or public.app_role_in(organization_id,
    array['org_owner','hq_admin','area_manager','store_manager']));

-- ---- テーブル配置（フロアマップエディタ用） ----
alter table public.restaurant_tables
  add column pos_x integer, -- グリッド座標（null=未配置→一覧グリッド表示）
  add column pos_y integer,
  add column shape text not null default 'square' check (shape in ('square','round','counter'));

-- ---- 顧客統合（Merge。重複候補はアプリ側で検出） ----
create or replace function public.merge_customers(p_keep_id uuid, p_merge_id uuid, p_note text default null)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_keep public.customers%rowtype;
  v_merge public.customers%rowtype;
begin
  if p_keep_id = p_merge_id then raise exception 'SAME_CUSTOMER'; end if;
  select * into v_keep from public.customers where id = p_keep_id for update;
  select * into v_merge from public.customers where id = p_merge_id for update;
  if v_keep.id is null or v_merge.id is null then raise exception 'CUSTOMER_NOT_FOUND'; end if;
  if v_keep.organization_id <> v_merge.organization_id then raise exception 'ORG_MISMATCH'; end if;
  if not public.app_role_in(v_keep.organization_id,
      array['org_owner','hq_admin','area_manager','store_manager']) then
    raise exception 'FORBIDDEN';
  end if;

  -- 参照の付替え
  update public.reservations set customer_id = p_keep_id where customer_id = p_merge_id;
  update public.orders set customer_id = p_keep_id where customer_id = p_merge_id;
  update public.customer_notes set customer_id = p_keep_id where customer_id = p_merge_id;
  update public.point_transactions set customer_id = p_keep_id where customer_id = p_merge_id;
  update public.coupon_redemptions set customer_id = p_keep_id where customer_id = p_merge_id;
  -- タグ・同意は重複を除いて移す
  insert into public.customer_tag_links (customer_id, tag_id)
    select p_keep_id, tag_id from public.customer_tag_links where customer_id = p_merge_id
  on conflict (customer_id, tag_id) do nothing;
  delete from public.customer_tag_links where customer_id = p_merge_id;
  delete from public.customer_consents where customer_id = p_merge_id;

  -- 集計・残高の統合
  update public.customers
  set visit_count = v_keep.visit_count + v_merge.visit_count,
      total_spent = v_keep.total_spent + v_merge.total_spent,
      cancel_count = v_keep.cancel_count + v_merge.cancel_count,
      no_show_count = v_keep.no_show_count + v_merge.no_show_count,
      point_balance = v_keep.point_balance + v_merge.point_balance,
      first_visit_at = least(v_keep.first_visit_at, v_merge.first_visit_at),
      last_visit_at = greatest(v_keep.last_visit_at, v_merge.last_visit_at),
      email = coalesce(v_keep.email, v_merge.email),
      name_kana = coalesce(v_keep.name_kana, v_merge.name_kana),
      birthday = coalesce(v_keep.birthday, v_merge.birthday),
      allergy_note = coalesce(v_keep.allergy_note, v_merge.allergy_note),
      updated_by = auth.uid()
  where id = p_keep_id;

  -- 統合元は論理削除（電話番号は重複回避のため退避）
  update public.customers
  set status = 'deleted',
      phone = case when phone is not null then phone || ':merged:' || substr(p_keep_id::text,1,8) end,
      service_note = coalesce(service_note || E'\n', '') || '[統合] ' || p_keep_id::text,
      updated_by = auth.uid()
  where id = p_merge_id;

  perform public.log_audit(v_keep.organization_id, null, 'customer.merge',
    'customers', p_keep_id::text,
    jsonb_build_object('merged_from', p_merge_id,
      'merged_name', v_merge.name, 'merged_phone', v_merge.phone),
    jsonb_build_object('visit_count', v_keep.visit_count + v_merge.visit_count,
      'total_spent', v_keep.total_spent + v_merge.total_spent), p_note);

  return jsonb_build_object('ok', true);
end $$;

-- ---- 打刻厳密化 v2: 休憩中フラグ・休憩中退勤の自動処理 ----
alter table public.time_entries add column on_break boolean not null default false;

create or replace function public.apply_punch(
  p_store_id uuid, p_profile_id uuid, p_event_type text,
  p_source text default 'personal', p_via_pin boolean default false)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_store public.stores%rowtype;
  v_entry public.time_entries%rowtype;
  v_today date := (now() at time zone 'Asia/Tokyo')::date;
  v_last_break public.time_entry_events%rowtype;
  v_break_min integer;
  v_note text := null;
begin
  select * into v_store from public.stores where id = p_store_id;
  if not found then raise exception 'STORE_NOT_FOUND'; end if;
  if p_profile_id <> auth.uid() and not p_via_pin
     and not public.app_role_in(v_store.organization_id,
       array['org_owner','hq_admin','area_manager','store_manager']) then
    raise exception 'FORBIDDEN';
  end if;

  -- 日跨ぎ勤務: 当日にopenが無ければ前日のopenも対象にする
  select * into v_entry from public.time_entries
  where profile_id = p_profile_id and store_id = p_store_id
    and work_date in (v_today, v_today - 1) and status = 'open'
  order by work_date desc, created_at desc limit 1;

  if p_event_type = 'clock_in' then
    if found and v_entry.clock_out_at is null then raise exception 'ALREADY_CLOCKED_IN'; end if;
    -- 他店舗でopenのままなら二重出勤として拒否
    if exists (select 1 from public.time_entries
               where profile_id = p_profile_id and status = 'open' and clock_out_at is null
                 and work_date in (v_today, v_today - 1)) then
      raise exception 'ALREADY_CLOCKED_IN_ELSEWHERE';
    end if;
    insert into public.time_entries
      (organization_id, store_id, profile_id, work_date, clock_in_at, source, created_by)
    values (v_store.organization_id, p_store_id, p_profile_id, v_today, now(), p_source, auth.uid())
    returning * into v_entry;

  elsif p_event_type = 'clock_out' then
    if v_entry.id is null or v_entry.clock_in_at is null then raise exception 'NOT_CLOCKED_IN'; end if;
    if v_entry.on_break then
      -- 休憩中の退勤: 休憩を自動終了して退勤（警告として記録）
      select * into v_last_break from public.time_entry_events
      where time_entry_id = v_entry.id and event_type = 'break_start'
      order by occurred_at desc limit 1;
      if v_last_break.id is not null then
        v_break_min := ceil(extract(epoch from (now() - v_last_break.occurred_at)) / 60)::integer;
        v_note := '休憩未終了のまま退勤（休憩' || v_break_min || '分を自動確定）';
        update public.time_entries
        set break_minutes = break_minutes + v_break_min where id = v_entry.id;
      end if;
    end if;
    update public.time_entries
    set clock_out_at = now(), status = 'closed', on_break = false,
        note = case when v_note is not null
                    then coalesce(note || E'\n', '') || v_note else note end,
        updated_by = auth.uid()
    where id = v_entry.id;

  elsif p_event_type = 'break_start' then
    if v_entry.id is null then raise exception 'NOT_CLOCKED_IN'; end if;
    if v_entry.on_break then raise exception 'ALREADY_ON_BREAK'; end if;
    update public.time_entries set on_break = true where id = v_entry.id;

  elsif p_event_type = 'break_end' then
    if v_entry.id is null then raise exception 'NOT_CLOCKED_IN'; end if;
    if not v_entry.on_break then raise exception 'NOT_ON_BREAK'; end if;
    select * into v_last_break from public.time_entry_events
    where time_entry_id = v_entry.id and event_type = 'break_start'
    order by occurred_at desc limit 1;
    if v_last_break.id is not null then
      v_break_min := ceil(extract(epoch from (now() - v_last_break.occurred_at)) / 60)::integer;
      update public.time_entries
      set break_minutes = break_minutes + v_break_min, on_break = false
      where id = v_entry.id;
    else
      update public.time_entries set on_break = false where id = v_entry.id;
    end if;
  else
    raise exception 'INVALID_EVENT';
  end if;

  insert into public.time_entry_events
    (organization_id, store_id, profile_id, time_entry_id, event_type, source, via_pin)
  values
    (v_store.organization_id, p_store_id, p_profile_id, v_entry.id, p_event_type, p_source, p_via_pin);

  return jsonb_build_object('ok', true, 'entry_id', v_entry.id, 'event', p_event_type,
    'warning', v_note);
end $$;

-- ---- 整合性制約の追加 ----
-- 同一レジで同時にopenなセッションは1つだけ（同時開局の競合を排除）
create unique index idx_register_sessions_one_open
  on public.register_sessions(register_id) where status = 'open';
-- 金額・数量の不変条件
alter table public.payments add constraint payments_amount_positive check (amount > 0);
alter table public.refunds add constraint refunds_amount_positive check (amount > 0);
alter table public.order_items add constraint order_items_quantity_positive check (quantity > 0);
alter table public.reservations add constraint reservations_party_positive check (party_size > 0);
alter table public.invoices add constraint invoices_amount_nonnegative check (amount >= 0);

-- ---- 商品画像バケット（公開: QRメニュー・POSで表示） ----
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('menu-images', 'menu-images', true, 5242880,
        array['image/png','image/jpeg','image/webp'])
on conflict (id) do nothing;

create policy menu_images_read on storage.objects for select
  using (bucket_id = 'menu-images');
create policy menu_images_insert on storage.objects for insert
  with check (bucket_id = 'menu-images'
    and public.app_role_in(((storage.foldername(name))[1])::uuid,
      array['org_owner','hq_admin','area_manager','store_manager']));
create policy menu_images_delete on storage.objects for delete
  using (bucket_id = 'menu-images'
    and public.app_role_in(((storage.foldername(name))[1])::uuid,
      array['org_owner','hq_admin','area_manager','store_manager']));
