-- =============================================================
-- TENPO ONE — 00020 ネイティブ会計（複式簿記）基盤
-- 勘定科目・仕訳（借方=貸方をDBで強制）・月次締め・消費税率version・
-- 固定資産・銀行口座・法定ルールversion・証憑の会計連携
-- 方針: 外部会計SaaSを必須にしない。法定数値はハードコードしない。
-- =============================================================

-- ---- 勘定科目マスター ----
create table public.accounts (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id),
  code text not null,
  name text not null,
  category text not null check (category in ('asset','liability','equity','revenue','expense')),
  sub_type text, -- cash / bank / receivable / payable / inventory 等（出納帳・自動仕訳の対象判定）
  default_tax_treatment text not null default 'taxable_standard' check (default_tax_treatment in
    ('taxable_standard','taxable_reduced','non_taxable','tax_exempt','out_of_scope')),
  is_system boolean not null default false, -- 標準テンプレート由来（削除不可・名称変更可）
  sort_order integer not null default 0,
  status text not null default 'active' check (status in ('active','deleted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid,
  updated_by uuid,
  unique (organization_id, code)
);
create trigger trg_accounts_updated_at before update on public.accounts
  for each row execute function public.set_updated_at();

-- ---- 会計期間（月次締め） ----
create table public.accounting_periods (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id),
  month date not null, -- 月初日
  status text not null default 'open' check (status in ('open','closed')),
  closed_by uuid references public.profiles(id),
  closed_at timestamptz,
  reopened_by uuid references public.profiles(id),
  reopened_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, month)
);
create trigger trg_accounting_periods_updated_at before update on public.accounting_periods
  for each row execute function public.set_updated_at();

-- ---- 仕訳 ----
create table public.journal_entries (
  id uuid primary key default gen_random_uuid(),
  entry_no bigint generated by default as identity,
  organization_id uuid not null references public.organizations(id),
  store_id uuid references public.stores(id), -- null=本社/全社
  entry_date date not null,
  description text not null,
  status text not null default 'draft' check (status in ('draft','posted','voided')),
  source_type text not null default 'manual' check (source_type in
    ('manual','pos_sales','purchase','expense','petty_cash','payroll','bank','fixed_asset','correction','opening')),
  source_id text, -- 参照元（order/invoice/payroll_run等のID。再入力ゼロ連動の追跡）
  correction_of uuid references public.journal_entries(id), -- 修正仕訳の元仕訳
  posted_by uuid references public.profiles(id),
  posted_at timestamptz,
  void_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid,
  updated_by uuid
);
create index idx_journal_entries_org_date on public.journal_entries(organization_id, entry_date);
create index idx_journal_entries_source on public.journal_entries(source_type, source_id);
create index idx_journal_entries_store on public.journal_entries(store_id, entry_date);
create trigger trg_journal_entries_updated_at before update on public.journal_entries
  for each row execute function public.set_updated_at();

create table public.journal_entry_lines (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id),
  entry_id uuid not null references public.journal_entries(id) on delete cascade,
  line_no integer not null default 1,
  account_id uuid not null references public.accounts(id),
  side text not null check (side in ('debit','credit')),
  amount integer not null check (amount > 0),
  tax_treatment text not null default 'out_of_scope' check (tax_treatment in
    ('taxable_standard','taxable_reduced','non_taxable','tax_exempt','out_of_scope')),
  tax_amount integer not null default 0,
  store_id uuid references public.stores(id),
  vendor_id uuid references public.vendors(id),
  memo text,
  created_at timestamptz not null default now()
);
create index idx_jel_entry on public.journal_entry_lines(entry_id);
create index idx_jel_account on public.journal_entry_lines(account_id);
create index idx_jel_org on public.journal_entry_lines(organization_id);

-- ---- 消費税率のバージョン管理（ハードコード禁止。cypress管理のグローバルマスター） ----
create table public.consumption_tax_rates (
  id uuid primary key default gen_random_uuid(),
  treatment text not null check (treatment in ('taxable_standard','taxable_reduced')),
  rate numeric(5,2) not null,
  effective_from date not null,
  effective_to date, -- null=現行
  version text not null,
  note text,
  created_at timestamptz not null default now()
);
-- 現行制度の初期値（2019-10-01施行の10%/8%。改正時は新行を追加し旧行のeffective_toを設定）
insert into public.consumption_tax_rates (treatment, rate, effective_from, version, note) values
  ('taxable_standard', 10.00, '2019-10-01', '2019-10', '標準税率'),
  ('taxable_reduced', 8.00, '2019-10-01', '2019-10', '軽減税率（飲食料品等）');

-- ---- 法定ルールversion（所得税・社会保険・労働基準等の受け皿。値は専門家確認後に投入） ----
create table public.legal_rule_versions (
  id uuid primary key default gen_random_uuid(),
  rule_type text not null check (rule_type in
    ('income_tax','social_insurance_health','social_insurance_pension','employment_insurance',
     'care_insurance','labor_standard','depreciation','consumption_tax')),
  year integer not null,
  region text, -- 都道府県等（社会保険料率の地域差）
  effective_from date not null,
  effective_to date,
  parameters jsonb not null default '{}'::jsonb, -- 税額表・料率等（専門家レビュー後に投入）
  version text not null,
  status text not null default 'draft' check (status in ('draft','reviewed','active','superseded')),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid
);
create index idx_legal_rules on public.legal_rule_versions(rule_type, year, effective_from);
create trigger trg_legal_rule_versions_updated_at before update on public.legal_rule_versions
  for each row execute function public.set_updated_at();

-- ---- 固定資産（償却計算はrule version方式・エンジンは法令仕様確認後） ----
create table public.fixed_assets (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id),
  store_id uuid references public.stores(id),
  name text not null,
  acquired_on date not null,
  acquisition_cost integer not null check (acquisition_cost >= 0),
  useful_life_years integer,
  depreciation_method text not null default 'straight_line'
    check (depreciation_method in ('straight_line','declining_balance','non_depreciable')),
  depreciation_rule_version text, -- legal_rule_versions(depreciation) 参照
  status text not null default 'in_use' check (status in ('in_use','disposed','sold','deleted')),
  disposed_on date,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid,
  updated_by uuid
);
create trigger trg_fixed_assets_updated_at before update on public.fixed_assets
  for each row execute function public.set_updated_at();

-- ---- 銀行口座・取引（外部API不要。手入力/CSV取込→仕訳候補） ----
create table public.bank_accounts (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id),
  store_id uuid references public.stores(id),
  bank_name text not null,
  branch_name text,
  account_type text not null default 'ordinary' check (account_type in ('ordinary','checking','savings')),
  account_last4 text, -- 口座番号は末尾のみ保持（全桁は保存しない）
  holder_name text,
  account_id uuid references public.accounts(id), -- 対応する勘定科目（普通預金等）
  status text not null default 'active' check (status in ('active','deleted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid,
  updated_by uuid
);
create trigger trg_bank_accounts_updated_at before update on public.bank_accounts
  for each row execute function public.set_updated_at();

create table public.bank_transactions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id),
  bank_account_id uuid not null references public.bank_accounts(id),
  transacted_on date not null,
  description text not null,
  deposit integer not null default 0 check (deposit >= 0),
  withdrawal integer not null default 0 check (withdrawal >= 0),
  import_hash text, -- CSV再取込の重複検知（date+desc+amount のhash）
  journal_entry_id uuid references public.journal_entries(id),
  created_at timestamptz not null default now(),
  created_by uuid,
  check (deposit > 0 or withdrawal > 0)
);
create unique index idx_bank_tx_dedupe on public.bank_transactions(bank_account_id, import_hash)
  where import_hash is not null;
create index idx_bank_tx_account on public.bank_transactions(bank_account_id, transacted_on);

-- ---- 証憑の会計連携・改変検知 ----
alter table public.documents
  add column journal_entry_id uuid references public.journal_entries(id),
  add column content_hash text; -- アップロード時のSHA-256（改変検知の基盤）

-- 証憑ファイルの差し替え防止: file_path / content_hash は一度設定したら変更不可
create or replace function public.prevent_document_tamper()
returns trigger language plpgsql as $$
begin
  if old.file_path is not null and new.file_path is distinct from old.file_path then
    raise exception 'DOCUMENT_FILE_IMMUTABLE';
  end if;
  if old.content_hash is not null and new.content_hash is distinct from old.content_hash then
    raise exception 'DOCUMENT_HASH_IMMUTABLE';
  end if;
  return new;
end $$;
create trigger trg_documents_tamper before update on public.documents
  for each row execute function public.prevent_document_tamper();

-- 経費費目 → 勘定科目のマッピング（自動仕訳用）
alter table public.expense_accounts
  add column account_id uuid references public.accounts(id);

-- =============================================================
-- 整合性の強制
-- =============================================================

-- 確定済み仕訳の明細変更・削除を禁止（修正は correction 仕訳で行う）
create or replace function public.prevent_posted_line_mutation()
returns trigger language plpgsql as $$
declare v_status text;
begin
  select status into v_status from public.journal_entries
  where id = coalesce(new.entry_id, old.entry_id);
  if v_status = 'posted' then
    raise exception 'POSTED_ENTRY_IMMUTABLE';
  end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end $$;
create trigger trg_jel_immutable before insert or update or delete on public.journal_entry_lines
  for each row execute function public.prevent_posted_line_mutation();

-- 確定済み仕訳ヘッダの改変禁止（void への遷移と void_reason 以外）
create or replace function public.prevent_posted_entry_mutation()
returns trigger language plpgsql as $$
begin
  if old.status = 'posted' then
    if new.status = 'voided' then
      return new; -- 取消は許可（履歴保持・監査ログはRPC側）
    end if;
    if new.status is distinct from old.status
       or new.entry_date is distinct from old.entry_date
       or new.description is distinct from old.description
       or new.store_id is distinct from old.store_id then
      raise exception 'POSTED_ENTRY_IMMUTABLE';
    end if;
  end if;
  return new;
end $$;
create trigger trg_je_immutable before update on public.journal_entries
  for each row execute function public.prevent_posted_entry_mutation();

-- =============================================================
-- RPC
-- =============================================================

-- 標準勘定科目テンプレートの導入（冪等）
create or replace function public.install_standard_accounts(p_org uuid)
returns integer language plpgsql volatile security definer set search_path = public as $$
declare v_count integer := 0;
begin
  if not public.app_role_in(p_org, array['org_owner','hq_admin','hq_accounting']) then
    raise exception 'FORBIDDEN';
  end if;
  insert into public.accounts (organization_id, code, name, category, sub_type, default_tax_treatment, is_system, sort_order, created_by)
  select p_org, t.code, t.name, t.category, t.sub_type, t.tax, true, t.sort, auth.uid()
  from (values
    ('100','現金','asset','cash','out_of_scope',100),
    ('101','小口現金','asset','cash','out_of_scope',101),
    ('110','普通預金','asset','bank','out_of_scope',110),
    ('130','売掛金','asset','receivable','out_of_scope',130),
    ('140','仮払金','asset',null,'out_of_scope',140),
    ('141','立替金','asset',null,'out_of_scope',141),
    ('150','商品','asset','inventory','out_of_scope',150),
    ('200','買掛金','liability','payable','out_of_scope',200),
    ('210','未払金','liability','payable','out_of_scope',210),
    ('211','未払費用','liability','payable','out_of_scope',211),
    ('220','預り金','liability',null,'out_of_scope',220),
    ('300','元入金','equity',null,'out_of_scope',300),
    ('400','売上高','revenue',null,'taxable_standard',400),
    ('401','売上高（軽減税率）','revenue',null,'taxable_reduced',401),
    ('500','仕入高','expense',null,'taxable_reduced',500),
    ('510','給与手当','expense',null,'out_of_scope',510),
    ('511','法定福利費','expense',null,'out_of_scope',511),
    ('520','消耗品費','expense',null,'taxable_standard',520),
    ('521','水道光熱費','expense',null,'taxable_standard',521),
    ('522','地代家賃','expense',null,'taxable_standard',522),
    ('523','通信費','expense',null,'taxable_standard',523),
    ('524','広告宣伝費','expense',null,'taxable_standard',524),
    ('525','修繕費','expense',null,'taxable_standard',525),
    ('599','雑費','expense',null,'taxable_standard',599)
  ) as t(code, name, category, sub_type, tax, sort)
  on conflict (organization_id, code) do nothing;
  get diagnostics v_count = row_count;
  return v_count;
end $$;

-- 仕訳の確定（借方=貸方の検証・締め済み期間の拒否）
create or replace function public.post_journal_entry(p_entry_id uuid)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_entry public.journal_entries%rowtype;
  v_debit bigint;
  v_credit bigint;
  v_lines integer;
begin
  select * into v_entry from public.journal_entries where id = p_entry_id for update;
  if not found then raise exception 'ENTRY_NOT_FOUND'; end if;
  if v_entry.status <> 'draft' then raise exception 'ENTRY_NOT_DRAFT'; end if;
  if not public.app_role_in(v_entry.organization_id,
      array['org_owner','hq_admin','hq_accounting']) then
    raise exception 'FORBIDDEN';
  end if;
  -- 締め済み期間への計上禁止
  if exists (
    select 1 from public.accounting_periods
    where organization_id = v_entry.organization_id
      and month = date_trunc('month', v_entry.entry_date)::date
      and status = 'closed') then
    raise exception 'PERIOD_CLOSED';
  end if;

  select coalesce(sum(amount) filter (where side = 'debit'), 0),
         coalesce(sum(amount) filter (where side = 'credit'), 0),
         count(*)
  into v_debit, v_credit, v_lines
  from public.journal_entry_lines where entry_id = p_entry_id;

  if v_lines < 2 then raise exception 'INSUFFICIENT_LINES'; end if;
  if v_debit <> v_credit then
    raise exception 'UNBALANCED: debit=% credit=%', v_debit, v_credit;
  end if;

  update public.journal_entries
  set status = 'posted', posted_by = auth.uid(), posted_at = now(), updated_by = auth.uid()
  where id = p_entry_id;

  perform public.log_audit(v_entry.organization_id, v_entry.store_id, 'journal.post',
    'journal_entries', p_entry_id::text, null,
    jsonb_build_object('debit', v_debit, 'credit', v_credit, 'source', v_entry.source_type), null);
  return jsonb_build_object('ok', true, 'debit', v_debit, 'credit', v_credit);
end $$;

-- 確定済み仕訳の取消（履歴保持・修正仕訳の起点）
create or replace function public.void_journal_entry(p_entry_id uuid, p_reason text)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare v_entry public.journal_entries%rowtype;
begin
  select * into v_entry from public.journal_entries where id = p_entry_id for update;
  if not found then raise exception 'ENTRY_NOT_FOUND'; end if;
  if v_entry.status <> 'posted' then raise exception 'ENTRY_NOT_POSTED'; end if;
  if not public.app_role_in(v_entry.organization_id, array['org_owner','hq_admin','hq_accounting']) then
    raise exception 'FORBIDDEN';
  end if;
  if p_reason is null or length(trim(p_reason)) = 0 then raise exception 'REASON_REQUIRED'; end if;
  if exists (
    select 1 from public.accounting_periods
    where organization_id = v_entry.organization_id
      and month = date_trunc('month', v_entry.entry_date)::date
      and status = 'closed') then
    raise exception 'PERIOD_CLOSED';
  end if;

  update public.journal_entries
  set status = 'voided', void_reason = p_reason, updated_by = auth.uid()
  where id = p_entry_id;
  perform public.log_audit(v_entry.organization_id, v_entry.store_id, 'journal.void',
    'journal_entries', p_entry_id::text, null, jsonb_build_object('reason', p_reason), p_reason);
  return jsonb_build_object('ok', true);
end $$;

-- 月次締め / 締め解除（解除は上位権限+監査ログ）
create or replace function public.close_accounting_period(p_org uuid, p_month date)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
begin
  if not public.app_role_in(p_org, array['org_owner','hq_admin','hq_accounting']) then
    raise exception 'FORBIDDEN';
  end if;
  -- 下書き仕訳が残っている月は締め不可
  if exists (
    select 1 from public.journal_entries
    where organization_id = p_org and status = 'draft'
      and date_trunc('month', entry_date)::date = date_trunc('month', p_month)::date) then
    raise exception 'DRAFT_ENTRIES_REMAIN';
  end if;
  insert into public.accounting_periods (organization_id, month, status, closed_by, closed_at)
  values (p_org, date_trunc('month', p_month)::date, 'closed', auth.uid(), now())
  on conflict (organization_id, month)
  do update set status = 'closed', closed_by = auth.uid(), closed_at = now();
  perform public.log_audit(p_org, null, 'accounting.period_close',
    'accounting_periods', p_month::text, null, null, null);
  return jsonb_build_object('ok', true);
end $$;

create or replace function public.reopen_accounting_period(p_org uuid, p_month date, p_reason text)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
begin
  if not public.app_role_in(p_org, array['org_owner','hq_admin']) then
    raise exception 'FORBIDDEN';
  end if;
  if p_reason is null or length(trim(p_reason)) = 0 then raise exception 'REASON_REQUIRED'; end if;
  update public.accounting_periods
  set status = 'open', reopened_by = auth.uid(), reopened_at = now()
  where organization_id = p_org and month = date_trunc('month', p_month)::date;
  perform public.log_audit(p_org, null, 'accounting.period_reopen',
    'accounting_periods', p_month::text, null, jsonb_build_object('reason', p_reason), p_reason);
  return jsonb_build_object('ok', true);
end $$;

-- =============================================================
-- RLS
-- =============================================================
do $$
declare r record;
begin
  for r in
    select * from (values
      ('accounts'), ('accounting_periods'), ('journal_entries'), ('journal_entry_lines'),
      ('fixed_assets'), ('bank_accounts'), ('bank_transactions')
    ) as t(tbl)
  loop
    execute format('alter table public.%I enable row level security', r.tbl);
    execute format(
      'create policy %I_select on public.%I for select using (
         public.app_is_cypress_admin() or (public.app_is_org_member(organization_id)
         and public.app_role_in(organization_id, array[''org_owner'',''hq_admin'',''hq_accounting'',''area_manager'',''store_manager'',''external_accountant''])))',
      r.tbl, r.tbl);
    execute format(
      'create policy %I_write on public.%I for all using (
         public.app_is_cypress_admin() or public.app_role_in(organization_id,
           array[''org_owner'',''hq_admin'',''hq_accounting''])) with check (
         public.app_is_cypress_admin() or public.app_role_in(organization_id,
           array[''org_owner'',''hq_admin'',''hq_accounting'']))',
      r.tbl, r.tbl);
  end loop;
end $$;

-- 税率・法定ルール: 閲覧は認証済み全員、編集はcypressのみ（企業ユーザーは法定ルールを編集不可）
alter table public.consumption_tax_rates enable row level security;
create policy ctr_select on public.consumption_tax_rates for select using (auth.uid() is not null);
create policy ctr_write on public.consumption_tax_rates for all
  using (public.app_is_cypress_admin()) with check (public.app_is_cypress_admin());
alter table public.legal_rule_versions enable row level security;
create policy lrv_select on public.legal_rule_versions for select using (auth.uid() is not null);
create policy lrv_write on public.legal_rule_versions for all
  using (public.app_is_cypress_admin()) with check (public.app_is_cypress_admin());
